SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 1, 'Luciano Aparecido Dos Santos Faria', 'Rua Paulo Piovesani, 961', 'Jardim Progresso', 'Colorado','13.821.009-0' ,'10083420924',1,0,'Parana','12/11/1999 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 2, 'Paulo Henrique De Jesus Lima', 'Rua Vereador Albino Gonçalves, 840', 'Jardim Progresso', 'Colorado','13.820.793-5' ,'10077112997',1,0,'Parana','17/07/1997 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 3, 'Marcos Vinicius Moraes Dos Santos', 'Rua Vereador Albino Gonçalves, 670', 'Jardim Progresso', 'Colorado','' ,'100800089-25',1,0,'Parana','23/09/1998 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 4, 'Wanderlei Junior Ribeiro Bagateli', 'Rua Paulo Piovesani, 330', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 5, 'Andreina Vitoria Dos Santos Bezerra', 'Rua Vereador Albino Gonçalves, 1110', 'Jardim Progresso', 'Colorado','12.790.347-6' ,'093.399.249-16',1,0,'Parana','28/12/2001 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 6, 'Mibisia Ribeiro Bagateli', 'Rua Paulo Piovesani, 330', 'Jardim Progresso', 'Colorado','14.091.510-6' ,'100.769.979-52',1,0,'Parana','16/07/2001 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 7, 'Iara Santos De Souza', 'Rua Paulo Piovesani, 491', 'Jardim Progresso', 'Colorado','13.899.943-2' ,'109.287.639-19',1,0,'Parana','23/07/2001 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 8, 'Vitor Alessandro Bezerra De Oliveira', 'Rua Vereador Albino Gonçalves, 850', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','04/02/2002 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 9, 'Andressa Aparecida Dos Santos Bezerra', 'Rua Vereador Albino Gonçalves, 1110', 'Jardim Progresso', 'Colorado','12.790.350-6' ,'093.399-259-98',1,0,'Parana','25/04/2005 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 10, 'Luiz Henrique Aparecido Bezerra De Oliveira', 'Rua Vereador Albino Gonçalves, 850', 'Jardim Progresso', 'Colorado','13.856.023-6' ,'',1,0,'Parana','21/12/2006 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 11, 'Valdir Neto Temporine Alves Da Rocha', 'Rua Atilio Zanardi, S/N', 'Jardim Progresso', 'Colorado','' ,'021.052.776-59',1,0,'Parana','17/08/2000 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 12, 'Isamara Souza Neves', 'Rua Atilio Zanardi, 191', 'Jardim Progresso', 'Colorado','13.951.736-9' ,'110.219.359-30',1,0,'Parana','19/05/2000 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 13, 'Luan Aparecido Dos Santos Farias', 'Rua Paulo Piovesani, 961', 'Jardim Progresso', 'Colorado','13.821.069-3' ,'107.777.819-80',1,0,'Parana','05/11/1996 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 14, 'Paulo Henrique Marcon Ferreira', 'Rua Laurindo Assoni, 242', 'Jardim Progresso', 'Colorado','10.282.018-5' ,'',1,0,'Parana','29/11/1997 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 15, 'Anderson Oliveira Da Silva', 'Rua Vereador Albino Gonçalves, 61', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','12/08/2002 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 16, 'Lincon Naranti Dos Santos ', 'Rua Santa Adelia, 390', 'Jardim Progresso', 'Colorado','13.922.225-3' ,'095.195.689-21',1,0,'Parana','12/03/1999 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 17, 'Laila Almeida Pelais', 'Rua Das Margaridas, 210', 'Jardim Progresso', 'Colorado','14.084.976-6' ,'112.422.739-30',1,0,'Parana','23/01/2002 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 18, 'Giovana Pelais', 'Rua Das Margaridas, 210', 'Jardim Progresso', 'Colorado','14.084.223-0' ,'112.422.469-67',1,0,'Parana','22/10/1999 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 19, 'Anthony Moraes Dos Santos', 'Rua Vereador Albino Gonçalves, ', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','13/06/2002 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 20, 'Patrik Junior De Sousa Pereira', 'Avenida Atlantica, 161', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','18/02/2004 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 21, 'Lucas Amorim Cena Souza', 'Rua Parigot De Souza', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','30/04/2004 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 22, 'Mateus De Abreu Pereira', 'Rua Santa Edivergens, S/N', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','16/07/2003 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 23, 'Naiara Bianca Silva Pereira', 'Avenida Cruzeiro Do Sul, S/N', 'Jardim Gloria', 'Colorado','' ,'',1,0,'Parana','21/11/2005 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 24, 'Nayuri Beatriz Silva Pereira', 'Avenida Cruzeiro Do Sul, S/N', 'Jardim Gloria', 'Colorado','' ,'',1,0,'Parana','','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 25, 'Joyce Batista Dos Santos', '', 'Jardim Progresso', 'Colorado','10.874.446-4' ,'',1,0,'Parana','27/03/1997 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 26, 'Maicon Junior Paiva Coutinho', 'Rua Vereador Albino Gonçalves, 1150', 'Jardim Progresso', 'Colorado','10.874.446-4' ,'095.254.099-10',1,0,'Parana','31/05/1997 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 27, 'Gabriela Vitoria', 'Rua Moacir Ferrari, 140', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','15/01/2002 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 28, 'Welinton De Oliveira Espindola', 'Rua Vereador Albino Gonçalves, 430', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','03/10/2001 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 29, 'Cleison Rodrigo Silva', 'Rua Paulo Piovesani, 1131', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','10/05/1998 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 30, 'Roberto Dos Santos', 'Rua Adolfo Piffer, 15', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','19/10/1997 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 31, 'Gabriel Munhoz Da Silva', 'Gabriel Munhoz Da Silva', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','20/03/1998 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 32, 'Moises Munhoz Da Silva', 'Rua Vereador Albino Gonçalves, 710', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','17/02/2000 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 33, 'Jose Ricardo Balieiro Dos Santos', 'Rua Paulo Piovesani, 1021', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','15/11/2000 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 34, 'Mariana De Oliveira Espindola', 'Rua Vereador Albino Gonçalves, 1140', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','05/01/2005 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 35, 'Vinicius Dos Santos Messias Da Silva', 'Rua Paulo Piovesani, 1181', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','30/01/1997 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 36, 'Ana Luiza Santos Bosseto', 'Rua Atilio Zanardi, 167', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','04/11/2004 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 37, 'Jessica Cristina De Souza Neves', 'Rua Atilio Zanardi, 191', 'Jardim Progresso', 'Colorado','13.951.761-0' ,'110.219.239-23',1,0,'Parana','31/07/2001 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 39, 'Maria Eduarda De Souza Andrade', 'Rua São Paulo, 83', 'Jardim Progresso', 'Colorado','57.094.700-5' ,'106.211.019-66',1,0,'Parana','19/01/2001 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 40, 'Gabriel De Souza Mendes', 'Rua Paulo Piovezani, 1141', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','14/12/2005 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 41, 'Anderson Andrade Dos Santos', 'Rua Vereador Albino Gonçalves', 'Jardim Progresso', 'Colorado','14.227.194-0' ,'',1,0,'Parana','28/02/1998 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 42, 'Leonardo Pereira De Souza', 'Rua Vereador Albino Gonçalves', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','06/05/2002 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 43, 'Gabriel Lima Teixeira', 'Rua Paulo Piovesani, 381', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','25/09/2000 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 44, 'Brendon Henrique Mendes França', 'Rua Paulo Piovesani, 31', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','06/06/2001 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 45, 'Rodrigo Pelais Morengui', 'Rua Vereador Albino Gonçalves', 'Jardim Progresso', 'Colorado','39.576.608-4' ,'',1,0,'Parana','02/04/2002 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 46, 'Otavio Augusto Da Silva Santos', 'Rua Paulo Piovesani', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','26/10/2005 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 47, 'Gabriele Vitoria De Mello Romanoli', 'Rua Mario Divino Paiao', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','15/01/2002 00:00:00','FEMININO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 48, 'Joao Andre De Oliveira', 'Rua Atilio Zanardi, 191', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','11/04/2006 00:00:00','MASCULINO');
SET DATEFORMAT dmy;
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade,estado,DataNascimento,Sexo ) VALUES ( 49, 'Jeferson Junior Souza Neves', 'Rua Atilio Zanardi, 191', 'Jardim Progresso', 'Colorado','' ,'',1,0,'Parana','14/12/2004 00:00:00','MASCULINO');
