INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 1, 'Luciano Aparecido Dos Santos Faria', 'Rua Paulo Piovesani, 961', 'Jardim Progresso', 'Colorado','13.821.009-0' ,'10083420924',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 2, 'Paulo Henrique De Jesus Lima', 'Rua Vereador Albino Gonçalves, 840', 'Jardim Progresso', 'Colorado','13.820.793-5' ,'10077112997',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 3, 'Marcos Vinicius Moraes Dos Santos', 'Rua Vereador Albino Gonçalves, 670', 'Jardim Progresso', 'Colorado','' ,'100800089-25',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 4, 'Wanderlei Junior Ribeiro Bagateli', 'Rua Paulo Piovesani, 330', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 5, 'Andreina Vitoria Dos Santos Bezerra', 'Rua Vereador Albino Gonçalves, 1110', 'Jardim Progresso', 'Colorado','12.790.347-6' ,'093.399.249-16',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 6, 'Mibisia Ribeiro Bagateli', 'Rua Paulo Piovesani, 330', 'Jardim Progresso', 'Colorado','14.091.510-6' ,'100.769.979-52',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 7, 'Iara Santos De Souza', 'Rua Paulo Piovesani, 491', 'Jardim Progresso', 'Colorado','13.899.943-2' ,'109.287.639-19',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 8, 'Vitor Alessandro Bezerra De Oliveira', 'Rua Vereador Albino Gonçalves, 850', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 9, 'Andressa Aparecida Dos Santos Bezerra', 'Rua Vereador Albino Gonçalves, 1110', 'Jardim Progresso', 'Colorado','12.790.350-6' ,'093.399-259-98',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 10, 'Luiz Henrique Aparecido Bezerra De Oliveira', 'Rua Vereador Albino Gonçalves, 850', 'Jardim Progresso', 'Colorado','13.856.023-6' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 11, 'Valdir Neto Temporine Alves Da Rocha', 'Rua Atilio Zanardi, S/N', 'Jardim Progresso', 'Colorado','' ,'021.052.776-59',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 12, 'Isamara Souza Neves', 'Rua Atilio Zanardi, 191', 'Jardim Progresso', 'Colorado','13.951.736-9' ,'110.219.359-30',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 13, 'Luan Aparecido Dos Santos Farias', 'Rua Paulo Piovesani, 961', 'Jardim Progresso', 'Colorado','13.821.069-3' ,'107.777.819-80',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 14, 'Paulo Henrique Marcon Ferreira', 'Rua Laurindo Assoni, 242', 'Jardim Progresso', 'Colorado','10.282.018-5' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 15, 'Anderson Oliveira Da Silva', 'Rua Vereador Albino Gonçalves, 61', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 16, 'Lincon Naranti Dos Santos ', 'Rua Santa Adelia, 390', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 17, 'Laila Almeida Pelais', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 18, 'Giovana Pelais', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 19, 'Anthony Moraes Dos Santos', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 20, 'Patrik Junior De Sousa Pereira', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 21, 'Lucas Amorim Cena Souza', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 22, 'Mateus De Abreu Pereira', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 23, 'Naiara Bianca Silva Pereira', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 24, 'Nayuri Beatriz Silva Pereira', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 25, 'Joyce Batista Dos Santos', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 26, 'Maicon Junior Paiva Coutinho', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 27, 'Gabriela Vitoria', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 28, 'Welinton De Oliveira Espindola', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 29, 'Cleison Rodrigo Silva', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 30, 'Roberto Dos Santos', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 31, 'Gabriel Munhoz Da Silva', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 32, 'Moises Munhoz Da Silva', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 33, 'Jose Ricardo Balieiro Dos Santos', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 34, 'Mariana De Oliveira Espindola', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 35, 'Vinicius Dos Santos Messias Da Silva', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 36, 'Ana Luiza Santos Bosseto', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 37, 'Jessica Cristina De Souza Neves', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 38, 'Ana Beatriz Costa De Oliveira', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 39, 'Maria Eduarda De Souza Andrade', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 40, 'Gabriel De Souza Mendes', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 41, 'Anderson Andrade Dos Santos', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 42, 'Leonardo Pereira De Souza', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 43, 'Gabriel Lima Teixeira', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 44, 'Brendon Henrique Mendes França', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 45, 'Rodrigo Pelais Morengui', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 46, 'Otavio Augusto Da Silva Santos', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 47, 'Gabriele Vitoria De Mello Romanoli', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 48, 'Joao Andre De Oliveira', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);
INSERT INTO [dbo].[Pessoas] (NumeroFicha, Nome, Endereco, Bairro, Cidade, Rg, Cpf,Ativo,idade ) VALUES ( 49, 'Jeferson Junior Souza Neves', '', 'Jardim Progresso', 'Colorado','' ,'',1,0);

update [dbo].[Pessoas] set tipo='Pessoa';
