// <auto-generated />
namespace ArteVida.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class revisao03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(revisao03));
        
        string IMigrationMetadata.Id
        {
            get { return "201504181812258_revisao03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
