// <auto-generated />
namespace ArteVida.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RevisaoInstrutorPessoanulos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevisaoInstrutorPessoanulos));
        
        string IMigrationMetadata.Id
        {
            get { return "201505071456354_RevisaoInstrutorPessoanulos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
